# Generated by Django 5.0.1 on 2025-02-12 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('total_processing_time', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('processing_time', models.FloatField()),
                ('status', models.CharField(default='completed', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pdf_converter.processingjob')),
            ],
        ),
    ]
